<?php
require_once($server_path.'modules/chat/chat.php');
require_once($server_path.'modules/cms/cms.php');
require_once($server_path.'modules/comment/comment.php');
require_once($server_path.'modules/contactus/contactus.php');
require_once($server_path.'modules/dashboard/dashboard.php');
require_once($server_path.'modules/event/event.php');
require_once($server_path.'modules/export/export.php');
require_once($server_path.'modules/faq/faq.php');
require_once($server_path.'modules/location1/location1.php');
require_once($server_path.'modules/media/media.php');
require_once($server_path.'modules/mediaTemp/mediaTemp.php');
require_once($server_path.'modules/notification/notification.php');
require_once($server_path.'modules/oauth/oauth.php');
require_once($server_path.'modules/report/report.php');
require_once($server_path.'modules/resource/resource.php');
require_once($server_path.'modules/setting/setting.php');
require_once($server_path.'modules/licenses/licenses.php');
?>