<?php
require_once($server_path.'modules/chat/webservice.php');
require_once($server_path.'modules/cms/webservice.php');
require_once($server_path.'modules/comment/webservice.php');
require_once($server_path.'modules/contactus/webservice.php');
require_once($server_path.'modules/dashboard/webservice.php');
require_once($server_path.'modules/event/webservice.php');
require_once($server_path.'modules/export/webservice.php');
require_once($server_path.'modules/faq/webservice.php');
require_once($server_path.'modules/location1/webservice.php');
require_once($server_path.'modules/media/webservice.php');
require_once($server_path.'modules/mediaTemp/webservice.php');
require_once($server_path.'modules/notification/webservice.php');
require_once($server_path.'modules/oauth/webservice.php');
require_once($server_path.'modules/report/webservice.php');
require_once($server_path.'modules/resource/webservice.php');
require_once($server_path.'modules/setting/webservice.php');
require_once($server_path.'modules/licenses/webservice.php');
?>